services:
  mysql:
    image: mysql:9.1.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stock_exchange
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: management_container
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql_data:
